---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.7
  - name: debian-7.11
  - name: centos-7.3
  - name: centos-6.9
  - name: fedora-25
  - name: macos-10.12
    driver:
      box: macos-10.12
  - name: windows-10
    driver:
      box: windows-10

suites:
  - name: default
    run_list:
      - recipe[chef-dk_test]
  - name: remove
    run_list:
      - recipe[chef-dk_test::remove]
  - name: repo
    run_list:
      - recipe[chef-dk_test]
    attributes:
      chef_dk:
        source: repo
    excludes:
      - ubuntu-16.04
      - debian-8.7
      - debian-8
      - debian-7.11
      - debian-7
      - fedora-25
  - name: repo_remove
    run_list:
      - recipe[chef-dk_test::remove]
    attributes:
      chef_dk:
        source: repo
    excludes:
      - ubuntu-16.04
      - debian-8.7
      - debian-8
      - debian-7.11
      - debian-7
      - fedora-25
  - name: custom
    run_list:
      - recipe[chef-dk_test]
    attributes:
      chef_dk:
        source: https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.14.25-1_amd64.deb
    excludes:
      - ubuntu-16.04
      - debian-8.7
      - debian-8
      - debian-7.11
      - debian-7
      - centos-7.3
      - centos-7
      - centos-6.9
      - centos-6
      - fedora-25
      - macos-10.12
      - macos
      - windows-10
      - windows
