---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.6
  - name: debian-6.0.10
  - name: centos-6.5
  - name: macosx-10.8
  - name: macosx-10.9

suites:
  - name: default
    run_list:
      - recipe[chef-dk]
  - name: global_shell_init
    run_list:
      - recipe[chef-dk]
    attributes:
      chef_dk:
        global_shell_init: true
