---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-8.4
  - name: debian-7.10
  - name: centos-7.2
  - name: centos-6.7
  - name: fedora-23
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012

suites:
  - name: default
    run_list:
      - recipe[chef-dk_test]
  - name: remove
    run_list:
      - recipe[chef-dk_test::remove]
  - name: repo
    run_list:
      - recipe[chef-dk_test]
    attributes:
      chef_dk:
        source: repo
    excludes:
      - ubuntu-16.04
      - ubuntu-12.04
      - debian-8.4
      - debian-8
      - debian-7.10
      - debian-7
      - fedora-23
  - name: repo_remove
    run_list:
      - recipe[chef-dk_test::remove]
    attributes:
      chef_dk:
        source: repo
    excludes:
      - ubuntu-16.04
      - ubuntu-12.04
      - debian-8.4
      - debian-8
      - debian-7.10
      - debian-7
      - fedora-23
  - name: custom
    run_list:
      - recipe[chef-dk_test]
    attributes:
      chef_dk:
        source: https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.14.25-1_amd64.deb
    excludes:
      - ubuntu-16.04
      - ubuntu-12.04
      - debian-8.4
      - debian-8
      - debian-7.10
      - debian-7
      - centos-7.2
      - centos-7
      - centos-6.7
      - centos-6
      - fedora-23
      - macosx-10.10
      - macosx
      - windows-2012
      - windows
