---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-8.2
  - name: debian-7.9
  - name: debian-6.0.10
  - name: centos-7.2
  - name: centos-6.7
  - name: fedora-23
  - name: fedora-22
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012

suites:
  - name: default
    run_list:
      - recipe[chef-dk]
  - name: global_shell_init
    run_list:
      - recipe[chef-dk]
    attributes:
      chef_dk:
        global_shell_init: true
  - name: install_from_specific_url
    run_list:
      - recipe[chef-dk]
    attributes:
      chef_dk:
        package_url: https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.3.4-1_amd64.deb
    excludes:
      - ubuntu-15.10
      - ubuntu-12.04
      - debian-8.2
      - debian-8
      - debian-7.9
      - debian-7
      - debian-6.0.10
      - debian-6
      - centos-7.2
      - centos-7
      - centos-6.7
      - centos-6
      - fedora-23
      - fedora-22
      - macosx-10.10
      - macosx
      - windows-2012
      - windows
