language: objective-c
osx_image: xcode8
rvm: 2.3.1

branches:
  only:
    - master

install:
  - bundle install --without=development integration

before_script:
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - bundle exec kitchen test
